spring.application.name=user-order-service
server.port=8081
spring.datasource.url=${DB_URL:jdbc:mysql://cloudstore-db.cnegcciaanlr.eu-north-1.rds.amazonaws.com:3306/cloudstore_users?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:Valentino16!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=skavaraminlångahemliganyckel
jwt.expiration=${JWT_EXPIRATION:86400000}
